# Author: 2gab
# Source: https://github.com/
# Keyword: picom, visual effects, personal file, compositor
# Reference: https://wiki.archlinux.org/title/Picom

#################################
#             Shadows           #
#################################



#################################
#           Fading              #
#################################



#################################
#   Transparency / Opacity      #
#################################



#################################
#     Background-Blurring       #
#################################



#################################
#       General Settings        #
#################################


### rascunho
backend = "glx";
vsync = true;
inactive-opacity = 0.85;
active-opacity = 0.9;
frame-opacity = 0.7;

blur:
{
    method = "gaussian";
    strength = 10;
}

opacity-rule = [
	# enable rule
	"80:class_g *= 'kitty'",
	"80:class_g *= 'Emacs'",

	# disable rule
	"100:class_g *= 'firefox'", 
	"100:class_g *= 'okular'",
	"100:class_g *= 'Spotify'",
	"100:class_g *= 'discord'",
	"100:class_g *= 'thunderbird'",
	"100:class_g *= 'Gimp'",
	"100:class_g *= 'Shotcut'",
	"100:class_g *= 'Ardour'",
	"100:class_g *= 'libreoffice'",
	"100:class_g *= 'obs'",
	"100:class_g *= 'MuseScore'",
	"100:class_g *= 'Inkscape'",
	"100:class_g *= 'i3bar'"		
];
